trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: group-abc  
  - group: group-1

  - name: storageAccountName
    value: 'akash8147'

  - name: containerName
    value: 'newcontainer1'

  - name: artifactName
    value: 'repo-artifact'

stages:
- stage: Build
  displayName: 'Build and Publish Artifact'
  jobs:
  - job: BuildAndPublish
    displayName: 'Collect and Publish Files'
    steps:
    - checkout: self
      fetchDepth: 0

    - script: |
        echo "Collecting all repo files except .yml..."
        mkdir -p $(Build.ArtifactStagingDirectory)/package
        find . -type f ! -name "*.yml" ! -path "./$(Build.ArtifactStagingDirectory)/*" -exec cp --parents {} $(Build.ArtifactStagingDirectory)/package/ \;
        echo "Contents of package directory:"
        ls -R $(Build.ArtifactStagingDirectory)/package
      displayName: 'Copy Files Except .yml to Staging Directory'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/package'
        artifact: '$(artifactName)'
        publishLocation: 'pipeline'
      displayName: 'Publish Filtered Files as Artifact'

- stage: Upload
  displayName: 'Upload to Azure Blob'
  dependsOn: Build
  jobs:
  - job: UploadToBlob
    displayName: 'Upload to Blob Storage'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: '$(artifactName)'
        targetPath: '$(Pipeline.Workspace)/artifact'
      displayName: 'Download Artifact'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'my-service-connection'  # Replace with your actual service connection
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Uploading files to blob storage..."
          az storage blob upload-batch \
            --account-name "$(storageAccountName)" \
            --destination "$(containerName)" \
            --source "$(Pipeline.Workspace)/artifact" \
            --account-key "$(storageKey)" \
            --overwrite true
      env:
        storageAccountName: $(storageAccountName)
        containerName: $(containerName)
        storageKey: $(storageKey)
      displayName: 'Upload Files to Azure Blob Storage'
